using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PROG6212_ST10435542_POE.Models.Enums;
using PROG6212_ST10435542_POE.Models.ViewModels.HR;

namespace PROG6212_ST10435542_POE.Controllers
{
// As demonstrated by IIEVC School of Computer Science (2025), the Controller is responsible for managing admin-related actions such as adding add & edit lecturer financials, view & generate reports, and manage users
// Ive made the controllers to use the ViewModels, but no logic added to it. Just to make the View visisble in the browser. Used the same concepts adopted from CLDV6212 POE
    public class AdminController : Controller
    {
        // displays the form for HR to add new lecturer financial details
        public IActionResult AddLecturerFinancials()
        {
            var availableLecturerUsers = new List<SelectListItem> // mock data
            {
                new SelectListItem { Value = "1", Text = "Lecturer A (User ID: 1)" },
                new SelectListItem { Value = "2", Text = "Lecturer B (User ID: 2)" }
            };
            ViewBag.AvailableLecturerUsers = availableLecturerUsers;

            return View(new AddLecturerFinancialsViewModel());
        }

        // displays various reports generated by HR
        public IActionResult DisplayReports()
        {
            return View(new ReportsDisplayViewModel());
        }

        // displays the form for HR to edit existing lecturer financial details
        public IActionResult EditLecturerFinancials()
        {
            return View(new EditLecturerFinancialsViewModel
            {
                UserID = 1001,
                LecturerID = 101,
                LecturerName = "Natheer Jardien",
                HourlyRate = 165.00m,
                BankDetails = "Dummy Bank, Account: 123456789",
                DateHired = new DateTime(2023, 01, 15)
            });
        }

        // displays the form to generate invoices and other reports
        public IActionResult GenerateInvoiceReport()
        {
            var lecturers = new List<SelectListItem>
            {
                new SelectListItem { Value = "1", Text = "John Doe" },
                new SelectListItem { Value = "2", Text = "Jane Smith" }
            };
            ViewBag.Lecturers = new SelectList(lecturers, "Value", "Text");

            return View(new GenerateReportViewModel());
        }

        // displays a list of all users for HR to manage
        public IActionResult ManageUsers()
        {
            var sampleUsers = new List<UserManagementViewModel>
            {
                new UserManagementViewModel { UserID = 1, Username = "jdoe", Email = "jdoe@example.com", Role = UserRoleEnum.Lecturer, HasLecturerProfile = true, LecturerProfileID = 101 },
                new UserManagementViewModel { UserID = 2, Username = "asmith", Email = "asmith@example.com", Role = UserRoleEnum.ProgrammeCoordinator },
                new UserManagementViewModel { UserID = 3, Username = "mjones", Email = "mjones@example.com", Role = UserRoleEnum.AcademicManager }
            };

            return View(sampleUsers);
        }
    }
}

/* References:

IIEVC School of Computer Science, 2025. CLDV6212 Building a Modern Web App with Azure Table Storage & ASP.NET Core MVC - Part 1. [video online] 
Available at: <https://youtu.be/Txp7VYUMBGQ?si=5sD7TV0vS90-pPHY>
[Accessed 14 September 2025].

*/
